version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

executors:
  node16:
    docker:
      - image: 'cypress/base:16.13.2'

workflows:
  e2e-test:
    jobs:
      - cypress/install:
          build: npm run build
          executor: node16
          working_directory: frontend
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
      - cypress/run:
          requires:
            - cypress/install
          executor: node16
          working_directory: frontend
          pre-steps:
            - run: 'node -v && npm -v'
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          store_artifacts: true
          start: npm run cy:start
          wait-on: 'http://localhost:3000'
          parallel: true
          spec: cypress/integration/sample_tests_spec.tsx

      - cypress/run:
          requires:
            - cypress/install
          executor: node16
          working_directory: frontend
          pre-steps:
            - run: 'node -v && npm -v'
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package.json"
            }}
          store_artifacts: true
          start: npm run cy:start
          wait-on: 'http://localhost:3000'
          parallel: true
          spec: cypress/integration/sample_tests2_spec.tsx

